version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shop -d shop"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  web:
    build: .
    working_dir: /code
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 5 &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code:Z
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      PYTHONPATH: /code

  celery:
    build: .
    working_dir: /code
    command: >
      sh -c "
        sleep 10 &&
        celery -A config worker -l info
      "
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      PYTHONPATH: /code

  test:
    build: .
    working_dir: /code
    command: >
      sh -c "
        sleep 10 &&
        python manage.py test
      "
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      PYTHONPATH: /code

volumes:
  postgres_data: