version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  web:
    build: .
    working_dir: /code
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code:Z
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      PYTHONPATH: /code

  celery:
    build: .
    working_dir: /code
    command: celery -A config worker -l info
    depends_on:
      - db
      - rabbitmq
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      PYTHONPATH: /code

  test:
    build: .
    working_dir: /code
    command: python manage.py test
    depends_on:
      - db
      - rabbitmq
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      PYTHONPATH: /code

volumes:
  postgres_data: